# Generated by Django 3.2.22 on 2023-10-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20231025_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Persona',
        ),
    ]
