# Generated by Django 3.2.22 on 2023-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20231026_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.FileField(upload_to='usuarios/'),
        ),
    ]
